#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width   3
bspc config window_gap     12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#81A1C1'
bspc config normal_border_color '#2E3440'

bspc rule -a Zathura state=tiled
bspc rule -a URxvt state=floating
bspc rule -a Inkscape desktop=^2 follow=on

polybar example &
picom --config ~/.config/picom.conf &
nitrogen Pictures/background.png --set-auto
inkscape-figures watch
python3 ~/inkscape-shortcut-manager/main.py
